### ISSUE TITLE
BuildCookRun freezes when OSVR-Unreal plugin added and enabled in a project

### ISSUE THREAD

**Issue by Stormwind99** [OSVR/OSVR-Unreal#81] opened 2016-08-02 15:27 UTC
UE4 BuildCookRun on a Windows build machine (without OSVR SDK or Runtime installed on system) of a project where OSVR-Unreal plugin was added (source of latest version from master OSVR-Unreal branch) hangs.

Command:

```
BuildCookRun -clean -server -project=G:\windows-worker-1\game-build-windows\build\UnrealEngine4\GameProject\Descent.uproject -noP4 -platform=Win64 -serverplatform=Win64 -clientconfig=Shipping -serverconfig=Shipping -cook -allmaps -stage -pak -archive -archivedirectory=G:\windows-worker-1\game-build-windows\output -utf8output -buildmachine -crashreporter -compile
```

Log snippet up to hang:

```
109UE4Editor-Cmd: [2016.08.02-07.10.17:506][  0]LogTargetPlatformManager:Display: Building Assets For WindowsNoEditor
110UE4Editor-Cmd: [2016.08.02-07.10.17:506][  0]LogTargetPlatformManager:Display: Building Assets For WindowsServer
111UE4Editor-Cmd: [2016.08.02-07.10.18:005][  0]LogModuleManager:Warning: No filename provided for module ExampleDeviceProfileSelector
112UE4Editor-Cmd: [2016.08.02-07.10.18:005][  0]LogModuleManager:Warning: ModuleManager: Unable to load module 'ExampleDeviceProfileSelector' because the file 'G:/windows-worker-1/game-build-windows/build/UnrealEngine4/Engine/Binaries/Win64/' was not found.
113UE4Editor-Cmd: [2016.08.02-07.11.32:129][  0]LogMeshUtilities:Warning: Invalid vertex normals found for mesh. Forcing recomputation of vertex normals for MikkTSpace. Fix mesh or disable "Use MikkTSpace Tangent Space" to avoid forced recomputation of normals.
114UE4Editor-Cmd: Aug 02 08:11:40.990 notice [OSVR]: Log file created in C:\Users\buildbot\AppData\Local\OSVR\Logs
115UE4Editor-Cmd: 
116UE4Editor-Cmd: Aug 02 08:11:40.990 notice [OSVR]: Log file name starts with "UE4Editor-Cmd"
117UE4Editor-Cmd: 
118UE4Editor-Cmd: Aug 02 08:11:40.990 notice [OSVR]: Logging for G:\windows-worker-1\game-build-windows\build\UnrealEngine4\Engine\Binaries\Win64\UE4Editor-Cmd.exe
119UE4Editor-Cmd: 
120UE4Editor-Cmd: Aug 02 08:11:41.074 info [OSVR]: Z:\j\workspace\OSVR-Core-Build-Win\BIT\64\TRACING\OFF\VS\12\host\windows\src\osvr\ClientKit\ServerAutoStartC.cpp:70: The current server location is currently unknown. Assuming server is already running.
121UE4Editor-Cmd: 
122UE4Editor-Cmd: Aug 02 08:11:41.387 info [OSVR: com.osvr.unreal.plugin]: OSVR client context initialized for com.osvr.unreal.plugin
123UE4Editor-Cmd: 
124UE4Editor-Cmd: Aug 02 08:11:42.726 notice [OSVR: com.osvr.unreal.plugin]: Could not connect to OSVR server in the timeout period allotted of 200ms
125UE4Editor-Cmd: 
```

**Comment by JeroMiya** [comment] 2016-08-02 16:19
Notes to self:

Possible repro steps:
1. Remove `OSVR_SERVER_ROOT` environment variable. Alternatively change it to some path that doesn't exist? Or the broken multi-path value the older SDK installer set.
2. Attempt to start UE editor in OSVRUnreal project in debug mode. Does it hang like above?
3. If not, attempt to run command line above on OSVRUnreal project. Does it hang now?

Hopefully I don't get to step 3 as it will be harder to diagnose without a debugger.

**Comment by Stormwind99** [comment] 2016-08-02 18:58
Two possibilities I'm looking into:
1. Changing module types to "RuntimeNoCommandlet" - see https://docs.unrealengine.com/latest/INT/Programming/Plugins/
2. Adding IsRunningCommandlet() and IsRunningDedicatedServer() checks to OSVREntryPoint::OSVREntryPoint().

**Comment by JeroMiya** [comment] 2016-08-02 19:18
Will we be able to provide a blueprint API (currently disabled in the archive folder) if we set our module types to RuntimeNoCommandlet? If so, I'd recommend trying option 2.

I'm not able to reproduce the freeze in the editor, and I'm getting errors trying to build using your command line arguments (UnrealEngine master branch, about a week old):
![image](https://cloud.githubusercontent.com/assets/320332/17341750/093e07e8-58c4-11e6-9fd7-478e05f3bf8d.png)

**Comment by Stormwind99** [comment] 2016-08-02 20:51
Can you copy and paste the exact command line you tried?   

The backtrace from UBT above doesn't have enough info to tell what went wrong.

I don't remember any project-specific setup needed before the project can perform a shipping build cook, but maybe I've forgotten.

**Comment by Stormwind99** [comment] 2016-08-02 20:51
I also submitted pull request #82 which seems to work around this issue.

**Comment by JeroMiya** [comment] 2016-08-02 21:11
Looks like it was a bad build on my part. See note on that pull request, and then I can merge this fix. Thanks!

**Comment by JeroMiya** [comment] 2016-08-03 13:23
Merged! Thanks again!

**Closed as completed by JeroMiya** 2016-08-03 13:23 UTC
